apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-edu-goods-deployment
  namespace: k8s-edu-demo
spec:
  selector:
    matchLabels:
      app: k8s-edu-goods-app
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-edu-goods-app
        version: blue
    spec:
      containers:
        - name: k8s-edu-goods-app
          image: sjin2pio/k8s-edu:v0.0.7      # dockerhub image repository : repo/image명:Tag
          imagePullPolicy: IfNotPresent        # k8s 클러스터에 다운로드 된 이미지 없으면 다운 or Always
          ports:
            - name: http
              containerPort: 8080              # demo.jar 실행 포트
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30          # livenessProbe 체크 초기 지연
            periodSeconds: 10               # liveness probe 체크 주기
            timeoutSeconds: 1              # liveness probe 실패시 pod restart
            failureThreshold: 3             # liveness probe 실패시 pod restart 횟수
          resources:                           # pod 사용 리소스 설정 블록
            requests:                          # 생성시 필요한 최소 리소스
              cpu: "1"
              memory: "2Gi"
            limits:                            # pod가 사용 가능한 최대 리소스
              cpu: "1"
              memory: "2Gi"
          env:                                 # pod 내 환경 변수 설정
            - name: SPRING_PROFILES_ACTIVE     # spring profile 설정
              value: prod                      # 상용(prod) 환경
      imagePullSecrets:                        # dockerhub 이미지 pull 위한 secret
        - name: k8s-edu-dockerhub-secret