apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edu-goods-hpa
  namespace: k8s-edu-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-edu-goods-deployment
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30